apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-hello.fullname" . }}
  labels:
    {{- include "go-hello.labels" . | nindent 4 }}
data:
  config.yaml: |
    port: 8080

    time:
      format: "15:04"
